-- 숙박 정보
SELECT A.ACCOM_NO, R.ROOM_PRICE , A.CHECK_OUT - A.CHECK_IN
FROM MEMBER M
JOIN ACCOM_RESERVATION A ON M.MEMBER_NO = A.MEMBER_NO
JOIN ROOM R ON A.ROOM_NO = R.ROOM_NO
WHERE M.ID = ? AND A.CANCEL = 'N';

-- 출발비행기 정보
SELECT FR.FLIGHT_NO, F.FLIGHT_PRICE
FROM MEMBER M
JOIN FLIGHT_RESERVATION FR ON M.MEMBER_NO = FR.MEMBER_NO
JOIN FLIGHT F ON FR.DEPARTURE_FLIGHT = F.FLIGHT_NO
WHERE M.ID = ? AND FR.CANCEL_YN = 'N';

-- 도착비행기 정보
SELECT F.FLIGHT_NO, F.FLIGHT_PRICE
FROM MEMBER M
JOIN FLIGHT_RESERVATION FR ON M.MEMBER_NO = FR.MEMBER_NO
JOIN FLIGHT F ON FR.RETURN_FLIGHT = F.FLIGHT_NO
WHERE M.ID = ? AND FR.CANCEL_YN = 'N';

-- 렌트카 예약정보
SELECT C.CAR_NO, R.DAY_PRICE, C.RETURN_DATE-C.RENTAL_DATE
FROM MEMBER M
JOIN CAR_RESERVATION C ON M.MEMBER_NO = C.MEMBER_NO
JOIN RENTAL_CAR R ON C.RENTAL_NO = R.RENTAL_NO
WHERE M.ID = ? AND C.CANCEL_YN = 'N';

COMMIT;
-- 결제완료 추가
ALTER TABLE CAR_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N'; 
ALTER TABLE CAR_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ALTER TABLE ACCOM_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N'; 
ALTER TABLE ACCOM_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ALTER TABLE FLIGHT_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N' ; 
ALTER TABLE FLIGHT_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ROLLBACK;
ALTER TABLE CAR_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE ACCOM_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE FLIGHT_RESERVATION DROP COLUMN PAID_YN;






