INSERT INTO MEMBER VALUES(SEQ_MEMBER.NEXTVAL, 'JEJU', 'KH3', '관리자', '관리자', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
COMMIT;

ALTER TABLE MEMBER DROP CONSTRAINT SYS_C008384;
ALTER TABLE MEMBER ADD UNIQUE(ID, QUIT_YN);

UPDATE MEMBER SET EMAIL = 'JEJU@KH.COM' WHERE ID = 'JEJU';

ALTER TABLE MEMBER MODIFY (EMAIL NOT NULL);

INSERT INTO MEMBER VALUES(SEQ_MEMBER.NEXTVAL, 'wjdgks', '1234', '임정한', '정한', NULL, 'wjdgks4752@naver.com', DEFAULT, DEFAULT, DEFAULT);
commit;
