INSERT INTO MEMBER VALUES(SEQ_MEMBER.NEXTVAL, 'JEJU', 'KH3', '包府磊', '包府磊', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
COMMIT;

ALTER TABLE MEMBER DROP CONSTRAINT SYS_C008384;
ALTER TABLE MEMBER ADD UNIQUE(ID, QUIT_YN);