DROP SEQUENCE SEQ_ROOM;
CREATE SEQUENCE SEQ_ROOM NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_FLIGHT;
CREATE SEQUENCE SEQ_FLIGHT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_TRAVEL;
CREATE SEQUENCE SEQ_TRAVEL NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_QnA;
CREATE SEQUENCE SEQ_QnA NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_PAYMENT;
CREATE SEQUENCE SEQ_PAYMENT NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_FLIGHT_RESERVATION;
CREATE SEQUENCE SEQ_FLIGHT_RESERVATION NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_RENTAL_CAR;
CREATE SEQUENCE SEQ_RENTAL_CAR NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_SURVEY;
CREATE SEQUENCE SEQ_SURVEY NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_CAR_RESERVATION;
CREATE SEQUENCE SEQ_CAR_RESERVATION NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_ACCOM_RESERVATION;
CREATE SEQUENCE SEQ_ACCOM_RESERVATION NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_CAR;
CREATE SEQUENCE SEQ_CAR NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_ACCOM;
CREATE SEQUENCE SEQ_ACCOM NOCACHE NOCYCLE;

--°íÁ¤°ª ½ÃÄö½º ±»ÀÌ...?
--DROP SEQUENCE SEQ_FUEL;
--CREATE SEQUENCE SEQ_FUEL NOCACHE NOCYCLE;
--
--DROP SEQUENCE SEQ_ACCOM_AR_INFO;
--CREATE SEQUENCE SEQ_ACCOM_AR_INFO NOCACHE NOCYCLE;
--
--DROP SEQUENCE SEQ_ROOM_VIEW_INFO;
--CREATE SEQUENCE SEQ_ROOM_VIEW_INFO NOCACHE NOCYCLE;
--
--DROP SEQUENCE SEQ_CATEGORY;
--CREATE SEQUENCE SEQ_CATEGORY NOCACHE NOCYCLE;
--
--DROP SEQUENCE SEQ_PURPOSE;
--CREATE SEQUENCE SEQ_PURPOSE NOCACHE NOCYCLE;
--
--DROP SEQUENCE SEQ_GROUP;
--CREATE SEQUENCE SEQ_GROUP NOCACHE NOCYCLE;
--
--DROP SEQUENCE SEQ_LOCATION;
--CREATE SEQUENCE SEQ_LOCATION NOCACHE NOCYCLE;





