INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '마리나제주', '제주특별자치도 제주시 특별자치도, 금능남로 127', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '엠버서터 호텔', '제주 서귀포시 중문관광로72번길 75', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 4, '더퍼스트 제주', '제주 제주시 도령로 83', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '스카이브 호텔', '제주특별자치도 제주시 노연로 12', 'N', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '브릿지 호텔', '제주 서귀포시 1100로 453-95 WE호텔', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '나이스웨더', '제주 서귀포시 중문관광로72번길 100', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 4, '블루아일랜드', '제주 서귀포시 안덕면 산록남로 863', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '마운틴제주', '제주 서귀포시 막숙포로 118', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '라온제나', '제주 제주시 애월읍 애월해안로 394', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '수피아', '제주 서귀포시 동홍로 7', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 4, '그랜트 인 제주', '제주 서귀포시 동문로 42', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '제이로인', '제주 제주시 애월읍 애월해안로 554-6', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '제주로올래', '제주 서귀포시 태평로 363 헤이 서귀포', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '만다린러브', '제주 서귀포시 성산읍 고성오조로 94', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '그랜드 하얏트', '제주시 그랜읍 하얏리 443', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, 'KH호텔', '제주시 테헤란로 123-2', 'N', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '1DRAGON', '제주시 드라곤로 1', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '칼 호텔', '서귀포시 표선면 813', 'N', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '토스카나 호텔', '서귀포시 안덕면 29', 'N', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '댕냥호텔', '서귀포시 꼬리면 귀엽리 486', 'Y', 'H');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '제주 배드라이도', '제주시 구좌읍 293', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '혼저옵서예', '제주시 조천읍 003', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '예스존', '제주시 추자면 3', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '바우잰', '제주시 한림읍 12', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 2, '미르가온', '제주시 미르로 2', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '투용', '제주시 투용동 22', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '재주좋조', '서귀포시 우리읍 잘하리', 'Y', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 1, '가온누리', '서귀포시 성주청 32', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '백패커스', '서귀포시 남원읍 200', 'N', 'G');
INSERT INTO ACCOM VALUES(SEQ_ACCOM.NEXTVAL, 3, '올래스테이', '서귀포시 대정읍 30', 'N', 'G');
