CREATE TABLE FLIGHT_TIME(
    FLIGHT_TIME_NO NUMBER PRIMARY KEY
    , FLIGHT_NO NUMBER NOT NULL
    , DEPARTURE_DATE TIMESTAMP NOT NULL
    , ARRIVAL_DATE TIMESTAMP NOT NULL
    , FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO)
);

ALTER TABLE FLIGHT_RESERVATION DROP CONSTRAINT FK_FLIGHT_TO_FLIGHT_RESERVATION_1;

ALTER TABLE FLIGHT_RESERVATION
    ADD CONSTRAINT FK_FLIGHT_TO_FLIGHT_RESERVATION_1 FOREIGN KEY ( DEPARTURE_FLIGHT )
        REFERENCES FLIGHT_TIME ( FLIGHT_TIME_NO );
        
ALTER TABLE FLIGHT_RESERVATION DROP CONSTRAINT FK_FLIGHT_TO_FLIGHT_RESERVATION_2;

ALTER TABLE FLIGHT_RESERVATION
    ADD CONSTRAINT FK_FLIGHT_TO_FLIGHT_RESERVATION_2 FOREIGN KEY ( RETURN_FLIGHT )
        REFERENCES FLIGHT_TIME ( FLIGHT_TIME_NO );
        
DROP SEQUENCE SEQ_FLIGHT_TIME;
CREATE SEQUENCE SEQ_FLIGHT_TIME NOCACHE NOCYCLE;








