DROP TABLE "ROOM";

CREATE TABLE "ROOM" (
    "ROOM_NO"       NUMBER NOT NULL,
    "ACCOM_NO"      NUMBER NOT NULL,
    "ROOM_VIEW"     NUMBER NOT NULL,
    "ROOM_NAME"     VARCHAR2(30) NOT NULL,
    "ROOM_PRICE"    NUMBER NOT NULL,
    "CAPACITY"      NUMBER NOT NULL,
    "ANIMAL_YN"     CHAR(1) DEFAULT 'N' NOT NULL,
    "POOL__ABLE_YN" CHAR(1) NOT NULL
);

COMMENT ON COLUMN "ROOM"."ROOM_PRICE" IS
    '음수 불가능';

COMMENT ON COLUMN "ROOM"."CAPACITY" IS
    '1이상';

DROP TABLE "FLIGHT";

CREATE TABLE "FLIGHT" (
    "FLIGHT_NO"      NUMBER NOT NULL,
    "FLIGHT_NAME"    CHAR(6) NOT NULL,
    "DEPARTURE_TIME" TIMESTAMP NOT NULL,
    "ARRIVAL_TIME"   TIMESTAMP NOT NULL,
    "AIRLINE"        VARCHAR2(20) NOT NULL,
    "FLIGHT_PRICE"   NUMBER NOT NULL,
    "SEAT"           NUMBER NOT NULL,
    "DEP_AIRPORT"    VARCHAR(15) NOT NULL,
    "ARR_AIRPORT"    VARCHAR(15) NOT NULL
);

COMMENT ON COLUMN "FLIGHT"."FLIGHT_NO" IS
    '시퀀스 관리';

COMMENT ON COLUMN "FLIGHT"."FLIGHT_NAME" IS
    'CHAR(6)? VARCHAR2?';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
    "MEMBER_NO"   NUMBER NOT NULL,
    "ID"          VARCHAR2(20) UNIQUE NOT NULL,
    "PWD"         VARCHAR2(20) NOT NULL,
    "MEMBER_NAME" VARCHAR2(20) NOT NULL,
    "MEMBER_NICK" VARCHAR2(20) NOT NULL,
    "PHONE"       CHAR(13) ,
    "EMAIL"       VARCHAR2(30) ,
    "ENROLL_DATE" TIMESTAMP DEFAULT sysdate NOT NULL,
    "QUIT_YN"     CHAR(1) DEFAULT 'N' CHECK(QUIT_YN IN('Y','N')) NOT NULL,
    "POINT"       NUMBER DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS
    '시퀀스로 관리';

COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS
    '제약조건 CHECK';

DROP TABLE "TRAVEL";

CREATE TABLE "TRAVEL" (
    "TRAVEL_NO"      NUMBER NOT NULL,
    "RECOMMEND_TYPE" NUMBER NOT NULL,
    "THEME"          NUMBER NOT NULL,
    "CATEGORY"       NUMBER NOT NULL,
    "TRAVEL_NAME"    VARCHAR2(20) NOT NULL,
    "TRAVEL_ADDRESS" VARCHAR2(100) NOT NULL,
    "ACTIVITY_YN"    CHAR(1) NOT NULL,
    "TRAVEL_PRICE"   NUMBER NOT NULL,
    "ANIMAL_YN"      CHAR(1) NOT NULL,
    "TRAVEL_INFO"    VARCHAR2(200) NOT NULL,
    "TRAVEL_PHONE"   VARCHAR2(13) NOT NULL,
    "OPEN"           TIMESTAMP NULL,
    "CLOSED"         TIMESTAMP NULL,
    "CLOSED_DAY"     VARCHAR2(20) NULL,
    "LIKE_CNT"       NUMBER DEFAULT 0 NULL,
    "DELETE_YN"      CHAR(1) DEFAULT 'N' NOT NULL,
    "DELETE_DATE"    TIMESTAMP NULL
);

COMMENT ON COLUMN "TRAVEL"."TRAVEL_NO" IS
    '시퀀스로 관리';

COMMENT ON COLUMN "TRAVEL"."ACTIVITY_YN" IS
    '제약조건 CHECK';

COMMENT ON COLUMN "TRAVEL"."ANIMAL_YN" IS
    '제약조건 CHECK
상세페이지에 추가';

COMMENT ON COLUMN "TRAVEL"."TRAVEL_PHONE" IS
    '000-0000-0000';

COMMENT ON COLUMN "TRAVEL"."LIKE_CNT" IS
    '좋아요는 시퀀스 말고 셀렉해서 +1 하는 걸로 (시퀀스로 하면 내려가는 기능을 쓸 수 없기 때문에 좋아요 눌렀다가 취소 못함)';

DROP TABLE "QnA";

CREATE TABLE "QnA" (
    "QUESTION_NO"    NUMBER NOT NULL,
    "MEMBER_NO"      NUMBER NOT NULL,
    "QUESTION_TITLE" VARCHAR(20) NOT NULL,
    "QUESTION_TIME"  TIMESTAMP DEFAULT sysdate NOT NULL,
    "ANSWER_YN"      CHAR(1) DEFAULT 'N' CHECK( ANSWER_YN IN('Y','N')) NOT NULL,
    "Q_CONTENT"      VARCHAR(4000) NOT NULL,
    "A_CONTENT"      VARCHAR(4000) NULL,
    "MODIFY_TIME"    TIMESTAMP NULL,
    "DELETE_YN"      CHAR(1) DEFAULT 'N' CHECK( DELETE_YN IN('Y','N')) NOT NULL,
    "DELETE_DATE"    TIMESTAMP NULL,
    "ANSWER_DATE"    TIMESTAMP NULL
);

COMMENT ON COLUMN "QnA"."QUESTION_NO" IS
    '시퀀스로 관리';

COMMENT ON COLUMN "QnA"."ANSWER_YN" IS
    'CHECK 제약조건';

COMMENT ON COLUMN "QnA"."DELETE_YN" IS
    'CHECK제약조건';

DROP TABLE "PAYMENT";

CREATE TABLE "PAYMENT" (
    "PAY_NO"      NUMBER NOT NULL,
    "FLIGHT_NO"   NUMBER NOT NULL,
    "ACCOM_NO"    NUMBER NOT NULL,
    "CAR_NO"      NUMBER NULL,
    "TOTAL"       NUMBER NOT NULL,
    "POINT_USED"  NUMBER DEFAULT 0 NOT NULL,
    "CUT_PRICE"   NUMBER NULL,
    "POINT"       NUMBER NOT NULL,
    "PAY_METHOD"  CHAR(1) NOT NULL,
    "PAY_DATE"    TIMESTAMP DEFAULT sysdate NOT NULL,
    "CANCEL_YN"   CHAR(1) DEFAULT 'N' NULL,
    "CANCEL_DATE" TIMESTAMP NULL
);

COMMENT ON COLUMN "PAYMENT"."PAY_NO" IS
    '시퀀스로관리';

COMMENT ON COLUMN "PAYMENT"."CANCEL_YN" IS
    'CHECK제약조건';

DROP TABLE "FLIGHT_RESERVATION";

CREATE TABLE "FLIGHT_RESERVATION" (
    "FLIGHT_NO"    NUMBER NOT NULL,
    "DEPARTURE"    NUMBER NOT NULL,
    "RETURN"       NUMBER NOT NULL,
    "MEMBER_NO"    NUMBER NOT NULL,
    "RESERVE_DATE" DATE DEFAULT sysdate NOT NULL,
    "CANCEL_YN"    CHAR(1) DEFAULT 'N' NOT NULL,
    "CANCEL_DATE"  TIMESTAMP NULL
);

COMMENT ON COLUMN "FLIGHT_RESERVATION"."MEMBER_NO" IS
    '시퀀스로 관리';

DROP TABLE "RENTAL_CAR";

CREATE TABLE "RENTAL_CAR" (
    "RENTAL_NO" NUMBER NOT NULL,
    "CAR_NO"    NUMBER NOT NULL,
    "CAR_UQ"    VARCHAR(20) NOT NULL,
    "DAY_PRICE" NUMBER NOT NULL
);

DROP TABLE "SURVEY";

CREATE TABLE "SURVEY" (
    "SURVEY_NO"   NUMBER NOT NULL,
    "MEMBER_NO"   NUMBER NOT NULL,
    "PURPOSE"     NUMBER NOT NULL,
    "PURPOSE2"    NUMBER NOT NULL,
    "LOCATION"    NUMBER NOT NULL,
    "GROUP"       NUMBER NOT NULL,
    "BUDGET"      CHAR(1) NOT NULL,
    "ANIMAL_YN"   CHAR(1) NOT NULL,
    "SURVEY_DATE" TIMESTAMP DEFAULT sysdate NOT NULL,
    "DELETE_YN"   CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "SURVEY"."SURVEY_NO" IS
    '시퀀스로 관리';

COMMENT ON COLUMN "SURVEY"."MEMBER_NO" IS
    '시퀀스로 관리';

COMMENT ON COLUMN "SURVEY"."DELETE_YN" IS
    'CHECK 제약조건';

DROP TABLE "CAR_RESERVATION";

CREATE TABLE "CAR_RESERVATION" (
    "CAR_NO"       NUMBER NOT NULL,
    "RENTAL_NO"    NUMBER NOT NULL,
    "MEMBER_NO"    NUMBER NOT NULL,
    "RENTAL_DATE"  DATE NOT NULL,
    "RETURN_DATE"  DATE NOT NULL,
    "RESERVE_DATE" DATE DEFAULT sysdate NOT NULL,
    "INSURANCE"    VARCHAR(20) NULL,
    "CANCEL_DATE"  TIMESTAMP NULL,
    "CANCEL_YN"    CHAR(1) DEFAULT 'N' NULL
);

COMMENT ON COLUMN "CAR_RESERVATION"."MEMBER_NO" IS
    '시퀀스로 관리';

DROP TABLE "ACCOM_RESERVATION";

CREATE TABLE "ACCOM_RESERVATION" (
    "ACCOM_NO"     NUMBER NOT NULL,
    "ROOM_NO"      NUMBER NOT NULL,
    "MEMBER_NO"    NUMBER NOT NULL,
    "CHECK_IN"     TIMESTAMP NOT NULL,
    "CHECK_OUT"    TIMESTAMP NOT NULL,
    "RESERVE_DATE" TIMESTAMP DEFAULT sysdate NOT NULL,
    "CANCEL_YN"    CHAR(1) DEFAULT 'N' NOT NULL,
    "CANCEL_DATE"  TIMESTAMP NULL
);

COMMENT ON COLUMN "ACCOM_RESERVATION"."MEMBER_NO" IS
    '시퀀스로 관리';

DROP TABLE "CAR";

CREATE TABLE "CAR" (
    "CAR_NO"     NUMBER NOT NULL,
    "FUEL"       NUMBER NOT NULL,
    "CAR_NAME"   VARCHAR2(20) NOT NULL,
    "CAR_SIZE"   VARCHAR2(20) NOT NULL,
    "CAR_PERSON" NUMBER NOT NULL,
    "OPENABLE"   CHAR(1) NOT NULL
);

DROP TABLE "ACCOM";

CREATE TABLE "ACCOM" (
    "ACCOM_NO"      NUMBER NOT NULL,
    "ACCOM_AROUND"  NUMBER NOT NULL,
    "ACCOM_NAME"    VARCHAR2(40) NOT NULL,
    "ACCOM_ADDRESS" VARCHAR(100) NOT NULL,
    "POOL_YN"       CHAR(1) DEFAULT 'N' NOT NULL,
    "TYPE"          CHAR(1) NOT NULL
);

COMMENT ON COLUMN "ACCOM"."ACCOM_NO" IS
    '시퀀스로 관리';

COMMENT ON COLUMN "ACCOM"."ACCOM_ADDRESS" IS
    '제주시, 서귀포시 구분';

COMMENT ON COLUMN "ACCOM"."TYPE" IS
    '호텔 H, 게스트하우스 G';

DROP TABLE "GROUP";

CREATE TABLE "GROUP" (
    "NO"    NUMBER NOT NULL,
    "GROUP" VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN "GROUP"."GROUP" IS
    '가족, 연인, 혼자, 친구';

DROP TABLE "FUEL";

CREATE TABLE "FUEL" (
    "FUEL_NO" NUMBER NOT NULL,
    "FUEL"    VARCHAR(10) NOT NULL
);

DROP TABLE "PURPOSE";

CREATE TABLE "PURPOSE" (
    "NO"      NUMBER NOT NULL,
    "PURPOSE" VARCHAR2(10) NOT NULL
);

DROP TABLE "ACCOM_AR_INFO";

CREATE TABLE "ACCOM_AR_INFO" (
    "ACCOM_AR_NO" NUMBER NOT NULL,
    "ACCOM_AR"    VARCHAR2(10) NULL
);

COMMENT ON COLUMN "ACCOM_AR_INFO"."ACCOM_AR" IS
    '논밭, 바닷가, 도시, 숲속';

DROP TABLE "LOCATION";

CREATE TABLE "LOCATION" (
    "NO"       NUMBER NOT NULL,
    "LOCATION" VARCHAR2(10) NOT NULL
);

DROP TABLE "ROOM_VIEW_INFO";

CREATE TABLE "ROOM_VIEW_INFO" (
    "ROOM_VIEW_NO"   NUMBER NOT NULL,
    "ROOM_VIEW_INFO" VARCHAR2(10) NULL
);

COMMENT ON COLUMN "ROOM_VIEW_INFO"."ROOM_VIEW_INFO" IS
    '오션, 마운틴, 시티';

DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
    "NO"       NUMBER NOT NULL,
    "CATEGORY" VARCHAR(10) NOT NULL
);

ALTER TABLE "ROOM" ADD CONSTRAINT "PK_ROOM" PRIMARY KEY ( "ROOM_NO" );

ALTER TABLE "FLIGHT" ADD CONSTRAINT "PK_FLIGHT" PRIMARY KEY ( "FLIGHT_NO" );

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ( "MEMBER_NO" );

ALTER TABLE "TRAVEL" ADD CONSTRAINT "PK_TRAVEL" PRIMARY KEY ( "TRAVEL_NO" );

ALTER TABLE "QnA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY ( "QUESTION_NO" );

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY ( "PAY_NO" );

ALTER TABLE "FLIGHT_RESERVATION" ADD CONSTRAINT "PK_FLIGHT_RESERVATION" PRIMARY KEY ( "FLIGHT_NO" );

ALTER TABLE "RENTAL_CAR" ADD CONSTRAINT "PK_RENTAL_CAR" PRIMARY KEY ( "RENTAL_NO" );

ALTER TABLE "SURVEY" ADD CONSTRAINT "PK_SURVEY" PRIMARY KEY ( "SURVEY_NO" );

ALTER TABLE "CAR_RESERVATION" ADD CONSTRAINT "PK_CAR_RESERVATION" PRIMARY KEY ( "CAR_NO" );

ALTER TABLE "ACCOM_RESERVATION" ADD CONSTRAINT "PK_ACCOM_RESERVATION" PRIMARY KEY ( "ACCOM_NO" );

ALTER TABLE "CAR" ADD CONSTRAINT "PK_CAR" PRIMARY KEY ( "CAR_NO" );

ALTER TABLE "ACCOM" ADD CONSTRAINT "PK_ACCOM" PRIMARY KEY ( "ACCOM_NO" );

ALTER TABLE "GROUP" ADD CONSTRAINT "PK_GROUP" PRIMARY KEY ( "NO" );

ALTER TABLE "FUEL" ADD CONSTRAINT "PK_FUEL" PRIMARY KEY ( "FUEL_NO" );

ALTER TABLE "PURPOSE" ADD CONSTRAINT "PK_PURPOSE" PRIMARY KEY ( "NO" );

ALTER TABLE "ACCOM_AR_INFO" ADD CONSTRAINT "PK_ACCOM_AR_INFO" PRIMARY KEY ( "ACCOM_AR_NO" );

ALTER TABLE "LOCATION" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY ( "NO" );

ALTER TABLE "ROOM_VIEW_INFO" ADD CONSTRAINT "PK_ROOM_VIEW_INFO" PRIMARY KEY ( "ROOM_VIEW_NO" );

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ( "NO" );

ALTER TABLE "ROOM"
    ADD CONSTRAINT "FK_ACCOM_TO_ROOM_1" FOREIGN KEY ( "ACCOM_NO" )
        REFERENCES "ACCOM" ( "ACCOM_NO" );

ALTER TABLE "ROOM"
    ADD CONSTRAINT "FK_ROOM_VIEW_INFO_TO_ROOM_1" FOREIGN KEY ( "ROOM_VIEW" )
        REFERENCES "ROOM_VIEW_INFO" ( "ROOM_VIEW_NO" );

ALTER TABLE "TRAVEL"
    ADD CONSTRAINT "FK_GROUP_TO_TRAVEL_1" FOREIGN KEY ( "RECOMMEND_TYPE" )
        REFERENCES "GROUP" ( "NO" );

ALTER TABLE "TRAVEL"
    ADD CONSTRAINT "FK_PURPOSE_TO_TRAVEL_1" FOREIGN KEY ( "THEME" )
        REFERENCES "PURPOSE" ( "NO" );

ALTER TABLE "TRAVEL"
    ADD CONSTRAINT "FK_CATEGORY_TO_TRAVEL_1" FOREIGN KEY ( "CATEGORY" )
        REFERENCES "CATEGORY" ( "NO" );

ALTER TABLE "QnA"
    ADD CONSTRAINT "FK_MEMBER_TO_QnA_1" FOREIGN KEY ( "MEMBER_NO" )
        REFERENCES "MEMBER" ( "MEMBER_NO" );

ALTER TABLE "PAYMENT"
    ADD CONSTRAINT "FK_FLIGHT_RESERVATION_TO_PAYMENT_1" FOREIGN KEY ( "FLIGHT_NO" )
        REFERENCES "FLIGHT_RESERVATION" ( "FLIGHT_NO" );

ALTER TABLE "PAYMENT"
    ADD CONSTRAINT "FK_ACCOM_RESERVATION_TO_PAYMENT_1" FOREIGN KEY ( "ACCOM_NO" )
        REFERENCES "ACCOM_RESERVATION" ( "ACCOM_NO" );

ALTER TABLE "PAYMENT"
    ADD CONSTRAINT "FK_CAR_RESERVATION_TO_PAYMENT_1" FOREIGN KEY ( "CAR_NO" )
        REFERENCES "CAR_RESERVATION" ( "CAR_NO" );

ALTER TABLE "FLIGHT_RESERVATION"
    ADD CONSTRAINT "FK_FLIGHT_TO_FLIGHT_RESERVATION_1" FOREIGN KEY ( "DEPARTURE" )
        REFERENCES "FLIGHT" ( "FLIGHT_NO" );

ALTER TABLE "FLIGHT_RESERVATION"
    ADD CONSTRAINT "FK_FLIGHT_TO_FLIGHT_RESERVATION_2" FOREIGN KEY ( "RETURN" )
        REFERENCES "FLIGHT" ( "FLIGHT_NO" );

ALTER TABLE "FLIGHT_RESERVATION"
    ADD CONSTRAINT "FK_MEMBER_TO_FLIGHT_RESERVATION_1" FOREIGN KEY ( "MEMBER_NO" )
        REFERENCES "MEMBER" ( "MEMBER_NO" );

ALTER TABLE "RENTAL_CAR"
    ADD CONSTRAINT "FK_CAR_TO_RENTAL_CAR_1" FOREIGN KEY ( "CAR_NO" )
        REFERENCES "CAR" ( "CAR_NO" );

ALTER TABLE "SURVEY"
    ADD CONSTRAINT "FK_MEMBER_TO_SURVEY_1" FOREIGN KEY ( "MEMBER_NO" )
        REFERENCES "MEMBER" ( "MEMBER_NO" );

ALTER TABLE "SURVEY"
    ADD CONSTRAINT "FK_PURPOSE_TO_SURVEY_1" FOREIGN KEY ( "PURPOSE" )
        REFERENCES "PURPOSE" ( "NO" );

ALTER TABLE "SURVEY"
    ADD CONSTRAINT "FK_PURPOSE_TO_SURVEY_2" FOREIGN KEY ( "PURPOSE2" )
        REFERENCES "PURPOSE" ( "NO" );

ALTER TABLE "SURVEY"
    ADD CONSTRAINT "FK_LOCATION_TO_SURVEY_1" FOREIGN KEY ( "LOCATION" )
        REFERENCES "LOCATION" ( "NO" );

ALTER TABLE "SURVEY"
    ADD CONSTRAINT "FK_GROUP_TO_SURVEY_1" FOREIGN KEY ( "GROUP" )
        REFERENCES "GROUP" ( "NO" );

ALTER TABLE "CAR_RESERVATION"
    ADD CONSTRAINT "FK_RENTAL_CAR_TO_CAR_RESERVATION_1" FOREIGN KEY ( "RENTAL_NO" )
        REFERENCES "RENTAL_CAR" ( "RENTAL_NO" );

ALTER TABLE "CAR_RESERVATION"
    ADD CONSTRAINT "FK_MEMBER_TO_CAR_RESERVATION_1" FOREIGN KEY ( "MEMBER_NO" )
        REFERENCES "MEMBER" ( "MEMBER_NO" );

ALTER TABLE "ACCOM_RESERVATION"
    ADD CONSTRAINT "FK_ROOM_TO_ACCOM_RESERVATION_1" FOREIGN KEY ( "ROOM_NO" )
        REFERENCES "ROOM" ( "ROOM_NO" );

ALTER TABLE "ACCOM_RESERVATION"
    ADD CONSTRAINT "FK_MEMBER_TO_ACCOM_RESERVATION_1" FOREIGN KEY ( "MEMBER_NO" )
        REFERENCES "MEMBER" ( "MEMBER_NO" );

ALTER TABLE "CAR"
    ADD CONSTRAINT "FK_FUEL_TO_CAR_1" FOREIGN KEY ( "FUEL" )
        REFERENCES "FUEL" ( "FUEL_NO" );

ALTER TABLE "ACCOM"
    ADD CONSTRAINT "FK_ACCOM_AR_INFO_TO_ACCOM_1" FOREIGN KEY ( "ACCOM_AROUND" )
        REFERENCES "ACCOM_AR_INFO" ( "ACCOM_AR_NO" );