-- 숙박 정보
SELECT A.ACCOM_NO, R.ROOM_PRICE , TO_DATE(TO_CHAR(A.CHECK_OUT,'YYMMDD')) - TO_DATE(TO_CHAR(A.CHECK_IN,'YYMMDD')) AS DAYS
FROM MEMBER M
JOIN ACCOM_RESERVATION A ON M.MEMBER_NO = A.MEMBER_NO
JOIN ROOM R ON A.ROOM_NO = R.ROOM_NO
WHERE M.MEMBER_NO = 1 AND A.CANCEL_YN = 'N' AND A.PAID_YN = 'N';

SELECT A.ACCOM_NO
FROM MEMBER M
JOIN ACCOM_RESERVATION A ON M.MEMBER_NO = A.MEMBER_NO
WHERE M.MEMBER_NO = 1 AND A.CANCEL_YN = 'N' AND A.PAID_YN = 'N';

-- 출발비행기 정보
SELECT FR.FLIGHT_NO, F.FLIGHT_PRICE
FROM MEMBER M
JOIN FLIGHT_RESERVATION FR ON M.MEMBER_NO = FR.MEMBER_NO
JOIN FLIGHT F ON FR.DEPARTURE_FLIGHT = F.FLIGHT_NO
WHERE M.MEMBER_NO = 1 AND FR.CANCEL_YN = 'N' AND FR.PAID_YN = 'N';

SELECT FR.FLIGHT_NO
FROM MEMBER M
JOIN FLIGHT_RESERVATION FR ON M.MEMBER_NO = FR.MEMBER_NO
WHERE M.MEMBER_NO = 1 AND FR.CANCEL_YN = 'N' AND FR.PAID_YN = 'N';

-- 도착비행기 정보
SELECT F.FLIGHT_NO, F.FLIGHT_PRICE
FROM MEMBER M
JOIN FLIGHT_RESERVATION FR ON M.MEMBER_NO = FR.MEMBER_NO
JOIN FLIGHT F ON FR.RETURN_FLIGHT = F.FLIGHT_NO
WHERE M.MEMBER_NO = 1 AND FR.CANCEL_YN = 'N' AND FR.PAID_YN = 'N';

SELECT F.FLIGHT_NO
FROM MEMBER M
JOIN FLIGHT_RESERVATION FR ON M.MEMBER_NO = FR.MEMBER_NO
WHERE M.MEMBER_NO = 1 AND FR.CANCEL_YN = 'N' AND FR.PAID_YN = 'N';

-- 렌트카 예약정보
SELECT C.CAR_NO,C.INSURANCE, R.DAY_PRICE, TO_DATE(TO_CHAR(C.RETURN_DATE,'YYMMDD')) - TO_DATE(TO_CHAR(C.RENTAL_DATE,'YYMMDD')) AS DAYS
FROM MEMBER M
JOIN CAR_RESERVATION C ON M.MEMBER_NO = C.MEMBER_NO
JOIN RENTAL_CAR R ON C.RENTAL_NO = R.RENTAL_NO
WHERE M.MEMBER_NO = 1 AND C.CANCEL_YN = 'N' AND C.PAID_YN = 'N';

SELECT C.CAR_NO
FROM MEMBER M
JOIN CAR_RESERVATION C ON M.MEMBER_NO = C.MEMBER_NO
WHERE M.MEMBER_NO = 1 AND C.CANCEL_YN = 'N' AND C.PAID_YN = 'N';

-- 결제내역 저장
INSERT INTO PAYMENT(PAY_NO,FLIGHT_NO,ACCOM_NO,CAR_NO,TOTAL,POINT_USED,CUT_PRICE,POINT,PAY_METHOD) 
    VALUES(SEQ_PAYMENT.NEXTVAL,?,?,?,?,?,?,?,?');

-- 포인트 저장
UPDATE MEMBER SET POINT = ? WHERE MEMBER_NO = ?;

--멤버 더미
DELETE FROM MEMBER WHERE ID = 'WOON';
INSERT INTO MEMBER VALUES(1, 'WOON', 'KH3', 'WOON', 'WOON', NULL, NULL, DEFAULT, DEFAULT, 100,NULL);
COMMIT;

ROLLBACK;
-- 차량 예약 더미
DELETE FROM CAR_RESERVATION WHERE MEMBER_NO = 1;
INSERT INTO CAR_RESERVATION VALUES(1,1,1,'22/08/01','22/08/04',SYSDATE,1,NULL,'N','N');
INSERT INTO CAR_RESERVATION VALUES(2,2,1,'22/08/01','22/08/04',SYSDATE,2,NULL,'N','N');
INSERT INTO CAR_RESERVATION VALUES(3,3,1,'22/08/01','22/08/04',SYSDATE,3,NULL,'N','N');

-- 숙소 예약 더미
DELETE FROM ACCOM_RESERVATION WHERE MEMBER_NO = 1;
INSERT INTO ACCOM_RESERVATION VALUES(1,1,1,'22/08/01','22/08/04',SYSDATE,'N',NULL,DEFAULT);
INSERT INTO ACCOM_RESERVATION VALUES(2,2,1,'22/08/01','22/08/04',SYSDATE,'N',NULL,DEFAULT);
INSERT INTO ACCOM_RESERVATION VALUES(3,3,1,'22/08/01','22/08/04',SYSDATE,'N',NULL,DEFAULT);


-- 비행기 예약 더미
DELETE FROM FLIGHT_RESERVATION WHERE MEMBER_NO = 1;
INSERT INTO FLIGHT_RESERVATION VALUES(1,1,1,1,SYSDATE,'N',NULL,'N');
INSERT INTO FLIGHT_RESERVATION VALUES(2,2,2,1,SYSDATE,'N',NULL,'N');
INSERT INTO FLIGHT_RESERVATION VALUES(3,3,3,1,SYSDATE,'N',NULL,'N');

COMMIT;
-- 예약 테이블 결제완료 'Y'로 바꾸기
UPDATE CAR_RESERVATION SET PAID_YN = 'Y' WHERE CAR_NO = 1;
UPDATE ACCOM_RESERVATION SET PAID_YN = 'Y' WHERE ACCOM_NO = 1;
UPDATE FLIGHT_RESERVATION SET PAID_YN = 'Y' WHERE FLIGHT_NO = 1;

-- 예약 테이블 결제완료 'N'으로 바꾸기
UPDATE CAR_RESERVATION SET PAID_YN = 'N' WHERE CAR_NO = 1;
UPDATE ACCOM_RESERVATION SET PAID_YN = 'N' WHERE ACCOM_NO = 1;
UPDATE FLIGHT_RESERVATION SET PAID_YN = 'N' WHERE FLIGHT_NO = 1;
COMMIT;

-- 예약 테이블 데이터 삭제
DELETE FROM PAYMENT WHERE PAY_NO = 1;
DELETE FROM PAYMENT WHERE PAY_NO = 2;

-- 포인트 사용 적립 내역 조회
SELECT P.PAY_DATE, P.CUT_PRICE, P.POINT 
FROM PAYMENT P
JOIN FLIGHT_RESERVATION FR ON P.FLIGHT_NO = FR.FLIGHT_NO 
WHERE FR.MEMBER_NO = 1 
ORDER BY P.PAY_DATE DESC;
COMMIT;

-- 결제 내역
SELECT P.PAY_DATE, P.TOTAL, P.CUT_PRICE, P.POINT_USED, P.PAY_METHOD 
FROM PAYMENT P
JOIN FLIGHT_RESERVATION FR ON P.FLIGHT_NO = FR.FLIGHT_NO
JOIN PAY_METHOD_NO PM ON P.PAY_METHOD = PM.METHOD_NO
WHERE FR.MEMBER_NO = 1 
ORDER BY P.PAY_DATE DESC;
COMMIT;

SELECT TRAVEL_NO,TRAVEL_NAME,LIKE_CNT
FROM TRAVEL
WHERE LIKE_CNT = 0;
