SELECT TRAVEL_NO, RECOMMEND_TYPE, PURPOSE, C.CATEGORY, TRAVEL_NAME, TRAVEL_ADDRESS, ACTIVITY_YN, TRAVEL_PRICE, ANIMAL_YN, TRAVEL_INFO, TRAVEL_PHONE, OPEN, CLOSED, CLOSED_DAY, LIKE_CNT
FROM TRAVEL T JOIN CATEGORY C ON T.CATEGORY = C.NO JOIN PURPOSE P ON T.THEME = P.NO 
WHERE TRAVEL_NO = 33
ORDER BY TRAVEL_NO;

-- 좋아요 +1 해주는 구문
UPDATE TRAVEL SET LIKE_CNT =  LIKE_CNT + 1 WHERE TRAVEL_NO = ? ;

UPDATE TRAVEL SET like_cnt = 34 WHERE TRAVEL_NO= 1;

-- 설문조사 관련 구문
SELECT *
FROM TRAVEL;

-- 설문번호 , 회원넘버, 목적 1 2 , 지역, 인원, 예산, 반려동물유무
SELECT TRAVEL_NO, G.PERSON_GROUP ,P.PURPOSE, C.CATEGORY, TRAVEL_NAME, TRAVEL_ADDRESS, TRAVEL_PRICE, ANIMAL_YN
FROM TRAVEL T 
JOIN CATEGORY C ON T.CATEGORY = C.NO 
JOIN PURPOSE P ON T.THEME = P.NO 
JOIN PERSON_GROUP G ON T.RECOMMEND_TYPE = G.NO
WHERE P.PURPOSE = '식도락'
AND C.CATEGORY = '맛집'
AND TRAVEL_ADDRESS LIKE '%제주시%'
AND TRAVEL_PRICE > 5000
AND ANIMAL_YN = 'Y'
;




