SELECT * FROM CAR;
-- 자동차 조회
SELECT R.RENTAL_NO, T.CAR_SIZE, C.CAR_NAME, R.CAR_UQ , R.DAY_PRICE, R.OPENABLE
FROM CAR C
JOIN RENTAL_CAR R ON C.CAR_NO = R.CAR_NO
JOIN TB_SIZE T ON C.CAR_SIZE = T.SIZE_NO
WHERE R.RENTAL_NO NOT IN 
    (SELECT RENTAL_NO
     FROM CAR_RESERVATION
     WHERE RENTAL_DATE BETWEEN '220801' AND '220803'
     OR RETURN_DATE BETWEEN '220801' AND '220803') 
AND T.CAR_SIZE = '대형'
AND C.CAR_PERSON > 2
--AND R.DAY_PRICE > 12750
ORDER BY RENTAL_NO;

SELECT AVG(DAY_PRICE)
FROM RENTAL_CAR;

SELECT R.RENTAL_NO, T.CAR_SIZE, C.CAR_NAME, R.CAR_UQ , R.DAY_PRICE, C.CAR_PERSON,R.OPENABLE, F.FUEL   
FROM CAR C     
JOIN RENTAL_CAR R ON C.CAR_NO = R.CAR_NO   
JOIN TB_SIZE T ON C.CAR_SIZE = T.SIZE_NO   
JOIN FUEL F ON C.FUEL = F.FUEL_NO   
WHERE R.RENTAL_NO NOT IN     
(SELECT RENTAL_NO      
FROM CAR_RESERVATION     
WHERE CANCEL_YN = 'N' AND (RENTAL_DATE BETWEEN '220803' AND '220804'    
OR RETURN_DATE BETWEEN '220803' AND '220804'))    
AND C.CAR_PERSON > 2
AND C.CAR_SIZE = 2
ORDER BY RENTAL_NO;


-- 자동차 예약
-- 예약할 자동차
SELECT *
FROM RENTAL_CAR
WHERE RENTAL_NO = 25;
-- 대충 회원 만들고
DELETE FROM memeber;
DELETE FROM CAR_RESERVATION;
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'ADMIN',1234,'홍길동','관리자','010-1234-1234','qodbsdk@naver.com',SYSDATE,'N',0);
-- 이런식으로 예약,,?
INSERT INTO CAR_RESERVATION (CAR_NO, RENTAL_NO, MEMBER_NO, RENTAL_DATE, RETURN_DATE, RESERVE_DATE) VALUES (5,25,1,'220801','220803', SYSDATE);


-- 자동차 예약 변경
-- 일단 사용자 예약 조회
SELECT 예약.CAR_NO,RENTAL_NO, RENTAL_DATE, RETURN_DATE, RESERVE_DATE, 보험.INSURANCE, DAY_PRICE
FROM CAR_RESERVATION 예약
JOIN INSURANCE 보험 ON 예약.INSURANCE = 보험.INSURANCE_NO
JOIN RENTAL_CAR 렌트 USING(RENTAL_NO)
WHERE CANCEL_YN = 'N'
AND 예약.MEMBER_NO = 1
ORDER BY CAR_NO;


SELECT C.CAR_NAME, R.DAY_PRICE, R.OPENABLE, CR.RENTAL_DATE
FROM RENTAL_CAR R
JOIN CAR C USING(CAR_NO)
JOIN CAR_RESERVATION CR USING (RENTAL_NO)
WHERE CR.MEMBER_NO = 1;

SELECT C.CAR_NAME,T.CAR_SIZE,F.FUEL,R.CAR_UQ
FROM CAR C
JOIN RENTAL_CAR R USING(CAR_NO)
JOIN FUEL F ON C.FUEL = F.FUEL_NO
JOIN TB_SIZE T ON C.CAR_SIZE = T.SIZE_NO
WHERE R.RENTAL_NO = 13;


-- 예약 취소
UPDATE CAR_RESERVATION
SET CANCEL_YN = 'N'
WHERE MEMBER_NO = 1
AND CAR_NO = 8;

-- 예약 수정 날짜
UPDATE CAR_RESERVATION
SET INSURANCE = 3
WHERE MEMBER_NO = 1
AND CAR_NO = 8;
-- 예약 수정 보험
-- 내 예약 조회
SELECT C.CAR_NAME,T.CAR_SIZE,F.FUEL,R.CAR_UQ,R.OPENABLE
FROM CAR C JOIN RENTAL_CAR R USING(CAR_NO)
JOIN FUEL F ON C.FUEL = F.FUEL_NO
JOIN TB_SIZE T ON C.CAR_SIZE = T.SIZE_NO WHERE R.RENTAL_NO = 1;
commit;

ROLLBACK;