-- 결제완료 데이터
ALTER TABLE CAR_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE CAR_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N'; 
ALTER TABLE CAR_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ALTER TABLE ACCOM_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE ACCOM_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N'; 
ALTER TABLE ACCOM_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ALTER TABLE FLIGHT_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE FLIGHT_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N' ; 
ALTER TABLE FLIGHT_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
COMMIT;



-- 여행지 좋아요
UPDATE TRAVEL SET like_cnt=34 WHERE TRAVEL_NO=1;
UPDATE TRAVEL SET like_cnt=22 WHERE TRAVEL_NO=2;
UPDATE TRAVEL SET like_cnt=13 WHERE TRAVEL_NO=3;
UPDATE TRAVEL SET like_cnt=37 WHERE TRAVEL_NO=4;
UPDATE TRAVEL SET like_cnt=45 WHERE TRAVEL_NO=5;
UPDATE TRAVEL SET like_cnt=77 WHERE TRAVEL_NO=6;
UPDATE TRAVEL SET like_cnt=56 WHERE TRAVEL_NO=7;
UPDATE TRAVEL SET like_cnt=86 WHERE TRAVEL_NO=8;
UPDATE TRAVEL SET like_cnt=27 WHERE TRAVEL_NO=9;
UPDATE TRAVEL SET like_cnt=66 WHERE TRAVEL_NO=10;
UPDATE TRAVEL SET like_cnt=43 WHERE TRAVEL_NO=11;
UPDATE TRAVEL SET like_cnt=58 WHERE TRAVEL_NO=12;
UPDATE TRAVEL SET like_cnt=45 WHERE TRAVEL_NO=13;
UPDATE TRAVEL SET like_cnt=32 WHERE TRAVEL_NO=14;
UPDATE TRAVEL SET like_cnt=37 WHERE TRAVEL_NO=15;
UPDATE TRAVEL SET like_cnt=44 WHERE TRAVEL_NO=16;
UPDATE TRAVEL SET like_cnt=67 WHERE TRAVEL_NO=17;
UPDATE TRAVEL SET like_cnt=86 WHERE TRAVEL_NO=18;
UPDATE TRAVEL SET like_cnt=41 WHERE TRAVEL_NO=19;
UPDATE TRAVEL SET like_cnt=21 WHERE TRAVEL_NO=20;
UPDATE TRAVEL SET like_cnt=34 WHERE TRAVEL_NO=21;
UPDATE TRAVEL SET like_cnt=73 WHERE TRAVEL_NO=22;
UPDATE TRAVEL SET like_cnt=34 WHERE TRAVEL_NO=23;
UPDATE TRAVEL SET like_cnt=77 WHERE TRAVEL_NO=24;
UPDATE TRAVEL SET like_cnt=66 WHERE TRAVEL_NO=25;
UPDATE TRAVEL SET like_cnt=33 WHERE TRAVEL_NO=26;
UPDATE TRAVEL SET like_cnt=55 WHERE TRAVEL_NO=27;
UPDATE TRAVEL SET like_cnt=22 WHERE TRAVEL_NO=28;
UPDATE TRAVEL SET like_cnt=35 WHERE TRAVEL_NO=29;
UPDATE TRAVEL SET like_cnt=87 WHERE TRAVEL_NO=30;
UPDATE TRAVEL SET like_cnt=86 WHERE TRAVEL_NO=31;
UPDATE TRAVEL SET like_cnt=29 WHERE TRAVEL_NO=32;
UPDATE TRAVEL SET like_cnt=18 WHERE TRAVEL_NO=33;
UPDATE TRAVEL SET like_cnt=25 WHERE TRAVEL_NO=34;
UPDATE TRAVEL SET like_cnt=18 WHERE TRAVEL_NO=35;
UPDATE TRAVEL SET like_cnt=36 WHERE TRAVEL_NO=36;
UPDATE TRAVEL SET like_cnt=90 WHERE TRAVEL_NO=37;
UPDATE TRAVEL SET like_cnt=44 WHERE TRAVEL_NO=38;
UPDATE TRAVEL SET like_cnt=34 WHERE TRAVEL_NO=39;
UPDATE TRAVEL SET like_cnt=86 WHERE TRAVEL_NO=40;
UPDATE TRAVEL SET like_cnt=50 WHERE TRAVEL_NO=41;
UPDATE TRAVEL SET like_cnt=47 WHERE TRAVEL_NO=42;
UPDATE TRAVEL SET like_cnt=85 WHERE TRAVEL_NO=43;
UPDATE TRAVEL SET like_cnt=63 WHERE TRAVEL_NO=44;
UPDATE TRAVEL SET like_cnt=14 WHERE TRAVEL_NO=45;
UPDATE TRAVEL SET like_cnt=94 WHERE TRAVEL_NO=46;
UPDATE TRAVEL SET like_cnt=75 WHERE TRAVEL_NO=47;
UPDATE TRAVEL SET like_cnt=44 WHERE TRAVEL_NO=48;
UPDATE TRAVEL SET like_cnt=11 WHERE TRAVEL_NO=49;
UPDATE TRAVEL SET like_cnt=45 WHERE TRAVEL_NO=50;
UPDATE TRAVEL SET like_cnt=56 WHERE TRAVEL_NO=51;
UPDATE TRAVEL SET like_cnt=89 WHERE TRAVEL_NO=52;
UPDATE TRAVEL SET like_cnt=55 WHERE TRAVEL_NO=53;
UPDATE TRAVEL SET like_cnt=37 WHERE TRAVEL_NO=54;
UPDATE TRAVEL SET like_cnt=56 WHERE TRAVEL_NO=55;
UPDATE TRAVEL SET like_cnt=98 WHERE TRAVEL_NO=56;
UPDATE TRAVEL SET like_cnt=54 WHERE TRAVEL_NO=57;
UPDATE TRAVEL SET like_cnt=57 WHERE TRAVEL_NO=58;
UPDATE TRAVEL SET like_cnt=19 WHERE TRAVEL_NO=59;
UPDATE TRAVEL SET like_cnt=56 WHERE TRAVEL_NO=60;
UPDATE TRAVEL SET like_cnt=52 WHERE TRAVEL_NO=61;
UPDATE TRAVEL SET like_cnt=89 WHERE TRAVEL_NO=62;
UPDATE TRAVEL SET like_cnt=41 WHERE TRAVEL_NO=63;
UPDATE TRAVEL SET like_cnt=75 WHERE TRAVEL_NO=64;
UPDATE TRAVEL SET like_cnt=57 WHERE TRAVEL_NO=65;
UPDATE TRAVEL SET like_cnt=16 WHERE TRAVEL_NO=66;
UPDATE TRAVEL SET like_cnt=82 WHERE TRAVEL_NO=67;
UPDATE TRAVEL SET like_cnt=27 WHERE TRAVEL_NO=68;
UPDATE TRAVEL SET like_cnt=64 WHERE TRAVEL_NO=69;
UPDATE TRAVEL SET like_cnt=46 WHERE TRAVEL_NO=70;
UPDATE TRAVEL SET like_cnt=85 WHERE TRAVEL_NO=71;
UPDATE TRAVEL SET like_cnt=54 WHERE TRAVEL_NO=72;
UPDATE TRAVEL SET like_cnt=97 WHERE TRAVEL_NO=73;
COMMIT;

-- 여행지 무휴 -> NULL 변경
UPDATE TRAVEL SET CLOSED_DAY=NULL WHERE CLOSED_DAY='무휴';



-- 숙소 테이블 제약조건 수정
ALTER TABLE ACCOM_RESERVATION DROP COLUMN CANCEL_YN;
ALTER TABLE ACCOM_RESERVATION ADD CANCEL_YN CHAR(1) DEFAULT 'N';
ALTER TABLE ACCOM_RESERVATION ADD CHECK (CANCEL_YN IN ( 'N', 'Y' ));
COMMIT;

-- 보험 테이블 추가
ALTER TABLE car_reservation MODIFY insurance NUMBER;

DROP TABLE insurance;
CREATE TABLE insurance (
    insurance_no NUMBER NOT NULL,
    insurance    VARCHAR(20) NOT NULL
);

ALTER TABLE insurance ADD CONSTRAINT pk_insurance PRIMARY KEY ( insurance_no );
ALTER TABLE car_reservation
    ADD CONSTRAINT fk_insurance_to_car_reservation FOREIGN KEY (insurance)
            REFERENCES insurance ( insurance_no );

INSERT INTO insurance (insurance_no,insurance) VALUES (0, '보험안함');
INSERT INTO insurance (insurance_no,insurance) VALUES (1, '일반자차');
INSERT INTO insurance (insurance_no,insurance) VALUES (2, '완전자차');
INSERT INTO insurance (insurance_no,insurance) VALUES (3, '슈퍼자차');

-- 비행시간 칼럼 데이터 변경
ALTER TABLE FLIGHT_TIME MODIFY DEPARTURE_DATE DATE;
ALTER TABLE FLIGHT_TIME MODIFY ARRIVAL_DATE DATE;
COMMIT;

-- 지역 로케이션 데이터
INSERT INTO LOCATION VALUES (1, '제주시');
INSERT INTO LOCATION VALUES (2, '서귀포시');
INSERT INTO LOCATION VALUES (3, '제주전체');


-- 신용카드, 계좌이체 결제 테이블 생성, 넘버로 변경
ALTER TABLE PAYMENT MODIFY PAY_METHOD NUMBER;

DROP TABLE PAY_METHOD_NO;
CREATE TABLE PAY_METHOD_NO (
    METHOD_NO NUMBER PRIMARY KEY,
    METHOD    VARCHAR(12) NOT NULL
);
COMMIT;
ALTER TABLE PAYMENT
    ADD CONSTRAINT FK_PAY_METHOD_NO_TO_PAYMENT FOREIGN KEY (PAY_METHOD)
            REFERENCES PAY_METHOD_NO ( METHOD_NO );

INSERT INTO PAY_METHOD_NO VALUES (1, '신용카드');
INSERT INTO PAY_METHOD_NO VALUES (2, '계좌이체');

COMMIT;