-- 결제완료 데이터
ALTER TABLE CAR_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE CAR_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N'; 
ALTER TABLE CAR_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ALTER TABLE ACCOM_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE ACCOM_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N'; 
ALTER TABLE ACCOM_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
ALTER TABLE FLIGHT_RESERVATION DROP COLUMN PAID_YN;
ALTER TABLE FLIGHT_RESERVATION ADD PAID_YN CHAR(1) DEFAULT 'N' ; 
ALTER TABLE FLIGHT_RESERVATION ADD CHECK (PAID_YN IN('Y','N'));
COMMIT;


-- 숙소 테이블 제약조건 수정
ALTER TABLE ACCOM_RESERVATION DROP COLUMN CANCEL_YN;
ALTER TABLE ACCOM_RESERVATION ADD CANCEL_YN CHAR(1) DEFAULT 'N';
ALTER TABLE ACCOM_RESERVATION ADD CHECK (CANCEL_YN IN ( 'N', 'Y' ));
COMMIT;

-- 보험 테이블 추가
ALTER TABLE car_reservation MODIFY insurance NUMBER;

DROP TABLE insurance;
CREATE TABLE insurance (
    insurance_no NUMBER NOT NULL,
    insurance    VARCHAR(20) NOT NULL
);

ALTER TABLE insurance ADD CONSTRAINT pk_insurance PRIMARY KEY ( insurance_no );
ALTER TABLE car_reservation
    ADD CONSTRAINT fk_insurance_to_car_reservation FOREIGN KEY (insurance)
            REFERENCES insurance ( insurance_no );

INSERT INTO insurance (insurance_no,insurance) VALUES (0, '보험안함');
INSERT INTO insurance (insurance_no,insurance) VALUES (1, '일반자차');
INSERT INTO insurance (insurance_no,insurance) VALUES (2, '완전자차');
INSERT INTO insurance (insurance_no,insurance) VALUES (3, '슈퍼자차');

-- 비행시간 칼럼 데이터 변경
ALTER TABLE FLIGHT_TIME MODIFY DEPARTURE_DATE DATE;
ALTER TABLE FLIGHT_TIME MODIFY ARRIVAL_DATE DATE;
COMMIT;

-- 지역 로케이션 데이터
INSERT INTO LOCATION VALUES (1, '제주시');
INSERT INTO LOCATION VALUES (2, '서귀포시');
INSERT INTO LOCATION VALUES (3, '제주전체');


-- 신용카드, 계좌이체 결제 테이블 생성, 넘버로 변경
ALTER TABLE PAYMENT MODIFY PAY_METHOD NUMBER;

DROP TABLE PAY_METHOD_NO;
CREATE TABLE PAY_METHOD_NO (
    METHOD_NO NUMBER PRIMARY KEY,
    METHOD    VARCHAR(12) NOT NULL
);
COMMIT;
ALTER TABLE PAYMENT
    ADD CONSTRAINT FK_PAY_METHOD_NO_TO_PAYMENT FOREIGN KEY (PAY_METHOD)
            REFERENCES PAY_METHOD_NO ( METHOD_NO );

INSERT INTO PAY_METHOD_NO VALUES (1, '신용카드');
INSERT INTO PAY_METHOD_NO VALUES (2, '계좌이체');

COMMIT;

--------------- 220804 VER2 추가 완료 --------------------



